# .github/workflows/deploy.yml

name: Build and Deploy Jekyll site to GitHub Pages

on:
  # main ë¸Œëœì¹˜ì— pushë  ë•Œ ì‹¤í–‰ë©ë‹ˆë‹¤
  push:
    branches: ["main"] # master ë¸Œëœì¹˜ë¥¼ ì“´ë‹¤ë©´ "master"ë¡œ ë°”ê¿”ì£¼ì„¸ìš”

  # Actions íƒ­ì—ì„œ ìˆ˜ë™ìœ¼ë¡œ ì‹¤í–‰í•  ìˆ˜ë„ ìˆìŠµë‹ˆë‹¤
  workflow_dispatch:

# GitHub Pagesì— ë°°í¬í•  ìˆ˜ ìˆë„ë¡ ê¶Œí•œì„ ì„¤ì •í•©ë‹ˆë‹¤
permissions:
  contents: read
  pages: write
  id-token: write

# ë™ì‹œ ë°°í¬ë¥¼ í•˜ë‚˜ë§Œ í—ˆìš©í•˜ë„ë¡ ì„¤ì •í•©ë‹ˆë‹¤
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # ë¹Œë“œ ì‘ì—…
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
      - name: Setup Ruby and install gems ğŸ’
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # ì‚¬ìš©í•˜ëŠ” ë£¨ë¹„ ë²„ì „ì— ë§ê²Œ ì¡°ì ˆ ê°€ëŠ¥
          bundler-cache: true # ìë™ìœ¼ë¡œ Gemfileì˜ í”ŒëŸ¬ê·¸ì¸ë“¤ì„ ì„¤ì¹˜í•˜ê³  ìºì‹œí•©ë‹ˆë‹¤
      - name: Build with Jekyll ğŸ”§
        run: bundle exec jekyll build
      - name: Upload artifact ğŸ“¦
        uses: actions/upload-pages-artifact@v3 # ë¹Œë“œ ê²°ê³¼ë¬¼(_site í´ë”)ì„ ì—…ë¡œë“œí•©ë‹ˆë‹¤
        with:
          path: './_site'

  # ë°°í¬ ì‘ì—…
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # ë¹Œë“œ ì‘ì—…ì´ ëë‚˜ì•¼ ì‹¤í–‰ë©ë‹ˆë‹¤
    steps:
      - name: Deploy to GitHub Pages ğŸš€
        id: deployment
        uses: actions/deploy-pages@v4 # ì—…ë¡œë“œëœ ê²°ê³¼ë¬¼ì„ GitHub Pagesì— ë°°í¬í•©ë‹ˆë‹¤
